#### Elementwise operations

In [1]:
# sum of a scalar
import numpy as np
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [2]:
# division by a scalar
a/2

array([0.5, 1. , 1.5, 2. ])

In [3]:
# exponentiation
2**a, a**2

(array([ 2,  4,  8, 16], dtype=int32), array([ 1,  4,  9, 16]))

In [4]:
# difference of 2 arrays
b = np.ones(4)+1 # b = array([2.,2.,2.,2.])
print(b)
a - b

[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [5]:
# multiplication of 2 arrays
a * b

array([2., 4., 6., 8.])

In [6]:
# a more complex operation
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [7]:
c = np.ones((3, 3))
c * c # NOT matrix multiplication!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#matrix multiplication
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [9]:
#comparisons
a_ = np.array([1, 2, 3, 4])
b_ = np.array([4, 2, 2, 4])
print(a_ == b_)
print(a_ > b_)

[False  True False  True]
[False False  True False]


In [10]:
#logical operations
# the truth value of a OR b element-wise
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print(np.logical_or(a, b))
#logical comparisons
print(np.all([True, True, False]))
print(np.any([True, True, False]))
#comparison in place
a = np.zeros((100, 100))
print(np.any(a != 0))
print(np.all(a == a))

[ True  True  True False]
False
True
False
True


In [11]:
#transcendentals
a = np.linspace(1,10,10)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [12]:
# An upper triangular array
a = np.triu(np.ones((3, 3)), 1) # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
# Transpose of the array a
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [14]:
#extrema
x = np.array([1, 3, 2])
print(x.min()) # the minimum value
print(x.max()) # the maximum value
print(x.argmin()) # index of minimum
print(x.argmax()) # index of maximum

1
3
0
1


In [15]:
#sorting
a = np.array([[4, 3, 5], [1, 2, 1]])
print(a)
# Sort inplace
a.sort(axis=1)
print(a)

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
