###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA FUN MOOC on Python 

###### Training section

Broadcasting in python is a mecanism which duplicates a scalar or vector to perform elementwise operations on matrix or vectors

In [1]:
import numpy as np
A = np.random.rand(4,3)
print(A)

[[0.6422793  0.81783588 0.16265294]
 [0.16811229 0.66037123 0.20258652]
 [0.93656326 0.40860885 0.61712814]
 [0.99014385 0.33136491 0.14707008]]


For instance, we can broadcast a scalar b to add b to each element of A

In [2]:
b = 2
A + b

array([[2.6422793 , 2.81783588, 2.16265294],
       [2.16811229, 2.66037123, 2.20258652],
       [2.93656326, 2.40860885, 2.61712814],
       [2.99014385, 2.33136491, 2.14707008]])

to sum horizontally the elements of A, we can call sum on A with the argument axis = 1

In [3]:
A.sum(axis= 1)

array([1.62276812, 1.03107004, 1.96230025, 1.46857884])

to sum vertically, the argument is axis =0

We can do elementwise operations between a matrix with a vector thanks to python broadcasting.
Let's define a vector u as the vertical sum of all columns of A and use it on A

In [4]:
u = A.sum(axis = 0)
print(u)
print(u.shape)

[2.7370987  2.21818087 1.12943768]
(3,)


For security reshape u to force its shape (1,3). Defining a vector with only one dimension, leaving the other empty such as u is defined above, can have terrible cost in debugging.

In [5]:
u = u.reshape(1,3)
print(u.shape)

(1, 3)


divide A by u

In [6]:
div = A/u
print(div)

[[0.23465698 0.36869666 0.14401232]
 [0.06141989 0.29770847 0.17936937]
 [0.34217372 0.18420899 0.546403  ]
 [0.36174941 0.14938588 0.13021531]]


We have broadcasted vector u on each element of A

###### Exercise section

Exercise:
compute, for each values of A, its percentage in regard of the total column sum of A and store it in a object w

Lets define two matrix with different dimensions, (3, 1) and (1, 5)

In [7]:
col = np.arange(1, 4).reshape((3, 1))
print(col)

[[1]
 [2]
 [3]]


In [8]:
line = 100 * np.arange(1, 6)
print(line)

[100 200 300 400 500]


Add the two matrix col and line thanks to broadcasting

Broacasting base rules  
We can broadcast A and B when there is a dimension C which 'spreads' both these of A and B  
So we can only broadcast from 1 to n.  
If there is a dimension p> 1 dividing n,  we cannot broadcast from p to n.

Define  

A with dimensions  15 x 3 x 5  
B with dimensions  15 x 1 x 5  
verify A+B has dimensions 15 x 3 x 5  

Try also for 

B is dimensions 3 x 5  
B is dimensions 3 x 1  
B is dimensions 1  

Define A nd B with following dimensions and check if you can broadcast

A      2 x 1
B  8 x 4 x 3