###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA MOOC on FUN platform

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


###### Benchmark a vectorised and an non vectorized version of the dot product

In [2]:
b = np.random.rand(1000000)
c = np.random.rand(1000000)

import time
time1 = time.time()
d = np.dot(b, c)
print(d)
time2 = time.time()

print("runtime vectorized = " +str(1000*(time2-time1)) + "ms")

249876.4338733247
runtime vectorized = 33.006906509399414ms


In [3]:
time1 = time.time()

e = 0
for i in range(1000000):
    e += b[i]*c[i]
print(e)
time2 = time.time()
print("runtime non vectorized = " +str(1000*(time2-time1)) + "ms")

249876.43387332582
runtime non vectorized = 418.52760314941406ms


###### Exercises

Turn the following iterative method into a vectorized computation using numpy.
 
   - apply the exponential operation to each element of a vector u.
   - we will store the outputs in a vector w of same dimensions than u.    


In [4]:
import math
n=3
u = np.random.rand(n)
v = np.zeros((n, 1))

print(v)
print(u)

for i in range(n):
    v[i]= math.exp(u[i])
print(v)

[[0.]
 [0.]
 [0.]]
[0.63983142 0.19893107 0.03113384]
[[1.8961612 ]
 [1.22009786]
 [1.03162357]]


Do the same on a matrix A of dimension 4 by 3 and store the results in an object z.  
Generate A with the random method of numpy.

Compute Ax + b, assuming x is a vector of same length that A rows and b is a scalar.  
Generate A and x with the random method of numpy.